services:
  nginx-rtmp:
    image: tiangolo/nginx-rtmp:latest
    container_name: rtmp
    ports:
      - "1935:1935"
      - "8085:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./rtmp-recordings:/var/www/rtmp-recordings
      - ./hls:/var/www/hls

